# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('head_id', models.CharField(default='0', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('roll_no', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=64)),
                ('dob', models.DateField()),
                ('semester', models.IntegerField()),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Department')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=1)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('semester', models.IntegerField()),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Department')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=1)),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('salary', models.FloatField()),
                ('teaching_since', models.DateField()),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Teaches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Subject')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Teacher')),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Subject'),
        ),
        migrations.AddField(
            model_name='marks',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Student'),
        ),
        migrations.AddField(
            model_name='marks',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Subject'),
        ),
        migrations.AddField(
            model_name='classattendance',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Student'),
        ),
        migrations.AddField(
            model_name='classattendance',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Subject'),
        ),
        migrations.AlterUniqueTogether(
            name='teaches',
            unique_together=set([('teacher_id', 'subject_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='subjectsection',
            unique_together=set([('subject_id', 'section')]),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set([('subject_id', 'date')]),
        ),
        migrations.AlterUniqueTogether(
            name='marks',
            unique_together=set([('student_id', 'subject_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='classattendance',
            unique_together=set([('student_id', 'subject_id')]),
        ),
    ]
