# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 14:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20161116_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='head_id',
            field=models.CharField(default='NULL', max_length=16),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
