# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 02:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20161116_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classattendance',
            name='student_id',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='main.Student'),
        ),
        migrations.AlterField(
            model_name='classattendance',
            name='subject_id',
            field=models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.CASCADE, to='main.Subject'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='student_id',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='main.Student'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='subject_id',
            field=models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.CASCADE, to='main.Subject'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject_id',
            field=models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.CASCADE, to='main.Subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='dept_id',
            field=models.ForeignKey(db_column='dept_id', on_delete=django.db.models.deletion.CASCADE, to='main.Department'),
        ),
        migrations.AlterField(
            model_name='studentsection',
            name='student_id',
            field=models.OneToOneField(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='main.Student'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='dept_id',
            field=models.ForeignKey(db_column='dept_id', on_delete=django.db.models.deletion.CASCADE, to='main.Department'),
        ),
        migrations.AlterField(
            model_name='subjectsection',
            name='subject_id',
            field=models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.CASCADE, to='main.Subject'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='dept_id',
            field=models.ForeignKey(db_column='dept_id', on_delete=django.db.models.deletion.CASCADE, to='main.Department'),
        ),
        migrations.AlterField(
            model_name='teaches',
            name='subject_id',
            field=models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.CASCADE, to='main.Subject'),
        ),
        migrations.AlterField(
            model_name='teaches',
            name='teacher_id',
            field=models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE, to='main.Teacher'),
        ),
    ]
