# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20161117_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='post',
            field=models.CharField(default='Professor', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='head_id',
            field=models.CharField(max_length=16),
        ),
    ]
